# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ac1ee2f7892682c45a5fd1da9d3a238260c8ac5b33e5a08e5b238c6291921e7f20b3555b47f66d9d8a84e877853b1fb3d50880316c93410acc0f828a273d9ea

test:
  secret_key_base: b97524c15454135b5e472efea6e367452bc33e546575c85e46ea7b3e9d0af52421c87cb54f87f044246d7f8dcace2041863333edb16b003085b8c7083ddc20f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
